# Level 1 heading

This is a *paragraph* with sentences. This is a paragraph with sentences. This is a paragraph with sentences. This is a paragraph with sentences. This is a paragraph with sentences. This is a paragraph with sentences. This is a paragraph with sentences. This is a paragraph with sentences. This is a paragraph with sentences. 

If you want a **second** paragraph, leave a blank line. If you want a second paragraph, leave a blank line. If you want a second paragraph, leave a blank line. If you want a second paragraph, leave a blank line. If you want a second paragraph, leave a blank line. If you want a second paragraph, leave a blank line. If you want a second paragraph, leave a blank line. 

## Level 2 heading

- Bullet
- Point
- List 
  - second level indentation
  - second level indentation

### Level 3 heading
1. Numbered bullets
1. Numbered bullets
1. Numbered bullets

#### Level 4 heading
##### Level 5 heading
###### Level 6 heading 

> Block quote

# Types

In [1]:
import numpy as np

###### Each list in numpy array should have same number of elements (3x3, 4x4, etc.)

In [5]:
L = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype = float)

In [6]:
print(L)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [7]:
L.dtype

dtype('float64')

In [16]:
np.arange(9).reshape(3,3) +3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

###### High number not included in random (1,7)- returns either 1,2,3,4,5,6
###### Third number is how many times random number should be produced

In [21]:
np.random.randint(1,7, 2)

array([6, 4])

In [22]:
# Likert scale

likert = np.random.randint(1,8,1000)

In [23]:
np.mean(likert)

3.973

In [24]:
np.median(likert)

4.0

## Counts
****

In [28]:
# Peak at first 10 values
likert[:10]

array([4, 3, 7, 5, 6, 1, 4, 6, 4, 5])

In [29]:
# Unique values in array
np.unique(likert)

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
np.unique(likert, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7]),
 array([152, 135, 148, 135, 151, 141, 138], dtype=int64))